version: '3.9'

services:
  python_converter_bot:
    env_file:
      - ../.env
    build:
      dockerfile: docker/Dockerfile
      context: ../
    volumes:
      - /var/logs/python_converter_bot:/app/logs
    depends_on:
      - redis

  redis:
    image: redis:7.2.3
    restart: on-failure
    ports:
      - "6379:6379"